// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: fcd9ff140d
// Version Date: 2021-07-14T06:36:40Z

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "mithril-micro/vsrv/pb"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	CreateVideoEndpoint  endpoint.Endpoint
	GetVideoEndpoint     endpoint.Endpoint
	GetVideoListEndpoint endpoint.Endpoint
	UpdateVideoEndpoint  endpoint.Endpoint
	DeleteVideoEndpoint  endpoint.Endpoint
}

// Endpoints

func (e Endpoints) CreateVideo(ctx context.Context, in *pb.CreateVideoReq) (*pb.Video, error) {
	response, err := e.CreateVideoEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Video), nil
}

func (e Endpoints) GetVideo(ctx context.Context, in *pb.GetVideoReq) (*pb.Video, error) {
	response, err := e.GetVideoEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Video), nil
}

func (e Endpoints) GetVideoList(ctx context.Context, in *pb.GetVideoListReq) (*pb.GetVideoListRes, error) {
	response, err := e.GetVideoListEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetVideoListRes), nil
}

func (e Endpoints) UpdateVideo(ctx context.Context, in *pb.UpdateVideoReq) (*pb.UpdateVideoRes, error) {
	response, err := e.UpdateVideoEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.UpdateVideoRes), nil
}

func (e Endpoints) DeleteVideo(ctx context.Context, in *pb.DeleteVideoReq) (*pb.DeleteVideoRes, error) {
	response, err := e.DeleteVideoEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.DeleteVideoRes), nil
}

// Make Endpoints

func MakeCreateVideoEndpoint(s pb.VideoServiceServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.CreateVideoReq)
		v, err := s.CreateVideo(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetVideoEndpoint(s pb.VideoServiceServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetVideoReq)
		v, err := s.GetVideo(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetVideoListEndpoint(s pb.VideoServiceServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetVideoListReq)
		v, err := s.GetVideoList(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeUpdateVideoEndpoint(s pb.VideoServiceServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.UpdateVideoReq)
		v, err := s.UpdateVideo(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeDeleteVideoEndpoint(s pb.VideoServiceServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.DeleteVideoReq)
		v, err := s.DeleteVideo(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"CreateVideo":  {},
		"GetVideo":     {},
		"GetVideoList": {},
		"UpdateVideo":  {},
		"DeleteVideo":  {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "CreateVideo" {
			e.CreateVideoEndpoint = middleware(e.CreateVideoEndpoint)
		}
		if inc == "GetVideo" {
			e.GetVideoEndpoint = middleware(e.GetVideoEndpoint)
		}
		if inc == "GetVideoList" {
			e.GetVideoListEndpoint = middleware(e.GetVideoListEndpoint)
		}
		if inc == "UpdateVideo" {
			e.UpdateVideoEndpoint = middleware(e.UpdateVideoEndpoint)
		}
		if inc == "DeleteVideo" {
			e.DeleteVideoEndpoint = middleware(e.DeleteVideoEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"CreateVideo":  {},
		"GetVideo":     {},
		"GetVideoList": {},
		"UpdateVideo":  {},
		"DeleteVideo":  {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "CreateVideo" {
			e.CreateVideoEndpoint = middleware("CreateVideo", e.CreateVideoEndpoint)
		}
		if inc == "GetVideo" {
			e.GetVideoEndpoint = middleware("GetVideo", e.GetVideoEndpoint)
		}
		if inc == "GetVideoList" {
			e.GetVideoListEndpoint = middleware("GetVideoList", e.GetVideoListEndpoint)
		}
		if inc == "UpdateVideo" {
			e.UpdateVideoEndpoint = middleware("UpdateVideo", e.UpdateVideoEndpoint)
		}
		if inc == "DeleteVideo" {
			e.DeleteVideoEndpoint = middleware("DeleteVideo", e.DeleteVideoEndpoint)
		}
	}
}
