// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 68ba2c3132
// Version Date: 2021-06-08T17:59:18Z

package main

import (
	"flag"

	// This Service
	"mithril-micro/usrv/handlers"
	"mithril-micro/usrv/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	cfg := server.DefaultConfig
	cfg = handlers.SetConfig(cfg)

	server.Run(cfg)
}
